= 基本数据结构
natsufumij <natsufumij@yeah.net>
:toc:

== 简介

`程序=数据结构+算法`

在我们最开始学数据结构的时候，书上总会写着这样一句话。

确实如此，程序就等于数据结构加上算法，这点无论在任何程序都能成立。小至驱动程序大到操作系统这些都是最主要的内容。从第一个开始编写计算机程序开始，逐渐形成了很多不同的数据结构，比如列表、栈、队列、图、树等等……这些数据结构在经过适当变体或者加强之后，仍活跃在现如今的各种程序当中。

我们就来回顾以下这些从远古时期就存在并沿用至今的经典数据结构吧。

当前仍然使用的经典数据结构如下：

* 线性表：数组列表、链表列表（普通数据结构）
* 栈：在一些特殊算法中会使用到，比如中缀式数值计算等、树的无递归遍历等
* 队列：双端队列、树的无递归遍历、
* 图：在一些特殊算法中会使用到，比如查找路径等
* 树：排序树、查找树、B树、B+树、红黑树
* Hash：在存储和快速查找会使用到，比如Java的HashMap

我们一个一个地回顾这些经典数据结构，并在举例的几个例子中查看各个数据结构所带有的魅力吧？

== 栈
=== 栈的定义
栈是一种特殊的线性表，仅允许在一端进行LIFO(Last in First Out)，即后入先出操作，这一端称为 `栈顶` 。而最低端称为 `栈底` 。向一个栈放入元素称为 `入栈` ,压栈后，该元素自动称为新的栈顶。而从栈顶删除元素称为 `出栈` ，出栈后，栈顶会自动向下退一格，直到不存在元素，栈为空。

栈只有几个操作：

* 判空
* 入栈
* 出栈

=== 栈的使用场景

栈的使用场景相当广泛。包括中缀式数值计算，树的无递归遍历，操纵记录。

Java 集合中的 `Stack` 类为方法添加了 `synchronized` 关键字，从而达到多线程安全的目的，但是由于 为方法添加了 `synchronized` 关键字，相当于给对象加了个锁，在多线程访问时会有较大的性能损失，因此在 `Stack` 类的注释中也给出了，可以使用另一种 `Deque` 即双端队列实现 `LIFO` 的栈操作。

.示例1.中缀式数值计算
[source,java]
....
include::code/StackDemo1.java[]
....


== 队列
=== 队列的定义
栈是一种特殊的线性表，在一端(被称为 `队尾` )仅允许进行添加元素操作，在另一端(被称为 `队头` )仅允许进行抽出元素操作，是一种FIFO(First In First Out)，即先入先出操作。

在平常生活中，最为形象的就是排队。当你位于队列中，队头的人不断地结束业务办理，当然或许有些人会因为有急事直接在插在队头，当然这就是另一种特殊的队列（双端队列），若仅在双端队列的对头进行添加和抽出的操作，那么这个队列就会变成一个 `栈`，在这里我们暂时不详细讨论双端队列。

队列只有几个操作：

* 判空
* 入队
* 出队

在 Java 集合中, `LinkedList`、`ArrayDeque` 均实现了双端队列，区别在于内部实现的数据结构用的是数组还是链表，在随机访问、操作等多种常用场景时有所不同。

=== 队列的使用场景
队列有很多的使用场景。

队列在树的遍历中有着不错的优势，其优势是使代码摆脱较为晦涩的递归形式，使代码可以在一个函数里就可以将全部的树节点给遍历完成，省了一部分的函数堆栈。

.示例1.树的层序遍历
[source,java]
....
include::code/QueueDemo1.java[]
....
