= AsciiDoc 学习
Natsufumij <natsufumij@yeah.net>
v1.0, 2024-02-01
:toc:
:home-page: https://natsufumij.cn

== 趣闻？

作为一个程序员，最早接触的标记语言是 `XML`，随着时间的推移，`HTML` 和各种琳琅满目的编程语言和各种奇奇怪怪的标记语言相遇了。不过，今天的主角，是我编写本篇文章所使用的标记语言 `AsciiDoc` ，简称 `adoc`。

虽然曾经学习过一些 `Markdown` 的语法，希望其用作笔记或者日常的文本记述，但是因为其由于官方不标准和各种方言以及编辑器的实现不同，从而对其失去了相当多的信心。

作为一个倾向于标准，或者说是喜爱着标准的人来说，方言和各种乱七八糟且不知道是否被编辑器或者渲染器实现的扩展功能，是一种不确定的折磨。

就在这个时候，我接触到了 `AsciiDoc` 这个标记语法。

因为一次翻译的任务，我认识了这个标记语法，因为不太清楚它的地位以及对 `Markdown` 语法便捷性的喜爱，所以我甚至对它嗤之以鼻，认为它不是一个好东西。

当然，这是我个人的偏见与傲慢，再做完我的那次任务，我不止一次地再往上搜索了关于 `adoc` 和 `AsciiDoc` 的文章和网站，最后到达了https://asciidoc.org/[官方网站]。

其标准的定义深深地吸引了我，和 `Markdown` 不同的简洁语法，繁多的标准功能，这些都是让我能够重拾对标记语言的信心。

废话还是不多说了，接下来就用来感受一下这个标记语言的魅力吧。

（以下为参考官网的学习笔记，官网地址: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference）

== 常用标记

=== 段落

.段落

 段落不需要特殊的标记符号，一个段落由一行或多行文字组成。
 断开新的一行也不会形成新的段落。

 但是至少要空一行，以此来形成新的一个段落。

.显示效果
段落不需要特殊的标记符号，一个段落由一行或多行文字组成，断开新的一行也不会形成新的段落。

但是至少要空一行，以此来形成新的一个段落。

=== 文本格式

.强调

 它可以 *伤害* 我。
 但是我 _不能_ 屈服它。
 可以打字 `OK`。
 它 *_真的_* 要走。
 不能挽留吗？ 让我们 `*_试试_*`。

.显示效果
它可以 *伤害* 我。

但是我 _不能_ 屈服它。

可以打字 `OK`。

它 *_真的_* 要走。

不能挽留吗？ 让我们 `*_试试_*`。

=== 链接

.自动链接、URL标志、邮件标志
 
 https://asciidoctor.org - 自动链接
 https://asciidoctor.org[Asciidoctor]
 devel@discuss.example.org
 mailto:devel@discuss.example.org[Discuss]
 link:++https://example.org/?q=[a b]++[带特殊字符串的URL]
 https://example.org/?q=%5Ba%20b%5D[带特殊字符串的URL]
 link:index.html[Docs]
 <<趣闻？>> - 跨文本区块引用

.显示效果
https://asciidoctor.org - 自动的链接

https://asciidoctor.org[Asciidoctor]

devel@discuss.example.org

mailto:devel@discuss.example.org[Discuss]

link:++https://example.org/?q=[a b]++[带特殊字符串的URL]

https://example.org/?q=%5Ba%20b%5D[带特殊字符串的URL]

link:index.adoc[Docs]

<<AsciiDoc 学习>> - 跨文本区块引用
